game: e.o main.o 
	gcc main.o e.o -o game -lSDL -lSDL_image -lSDL_mixer  -lSDL_ttf -g
main.o:main.c
	gcc -c main.c -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf -g
e.o:e.c
	gcc -c e.c -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf -g



